### ISSUE TITLE
Pre-reorg cleanup and prep work

### ISSUE THREAD

**Issue by chalin** [grpc/grpc.io#224]
- [x] Remove "Guides" top-nav entry #222
- [x] Curate homepage CTA buttons #223, #225
- [x] Left-nav: support 3 levels, drop TOC and some cleanup #234
- [x] Drop `layout` front-matter entry from docs pages #235
- [x] Can't access language-specific pages on mobile #168
- [x] Display TOC somewhere other than the left sidenav #231
- Navigation sidebar cannot easily be scrolled #217 - will be addressed separately.

Under consideration:
- Rename "Guides" section
  - This will require that some pages, currently under Guides, be moved to elsewhere. It might require the creation of an Introduction or "What is gRPC" section.

**Comment by chalin** [comment]
All done!
