### ISSUE TITLE
Site reorg: add new Intro and Languages section, and more

### ISSUE THREAD

**Issue by chalin** [grpc/grpc.io#249]
- [x] Add Languages section, and reorg language-specific pages #181
  - [x] Docs top-nav dropdown menu: remove "Quick Start" and "Tutorial" #358
- [x] Add "What is gRPC" section, and reorg pages related to introductory material #250
- [x] Add API-reference subentries to sidenav #277
- [x] Drop "Packages" from the top nav #255.
  Closed by: Add "Daily builds" links for wrapped languages #283
- [x] Rework Docs landing page #256 
  - [x] Reworked Docs landing page #302
- Rename "Guides" to "Techniques" #254

Supporting:

- [x] Drop `contributing.md` placeholder file #248
- [x] Refer to C# entry as C# / .NET #258
- [x] Pre-reorg cleanup and prep work #224

**Comment by chalin** [comment]
All items have been addressed 🎉  except for #254, which (being in its own issue) will be tracked separately. Closing.
