### ISSUE TITLE
Analytics and SEO improvements

### ISSUE THREAD

**Issue by chalin** [grpc/grpc.io#362]
- [x] `sitemap.xml`: some pages don't have the following entries:
  - [x] `lastmod`
  - [→] `changefreq` #571
- [x] Add breadcrumbs for at least the language pages - #233
- [x] Make page titles unique - #363
    Not strictly required, but there is some SEO weirdness that is happening with the old base Quick-start page being automatically redirect to the Go Quick-start page. It might help if at least the Quick-start and Tutorial pages mentioned the language in the title.
- [x] examples/README: update links into grpc.io Java pages https://github.com/grpc/grpc-java/pull/7288
- [x] Add `google-site-verification` file #365 & #366
- [→] Consider using campaigns -- e.g., see [URL builders](https://support.google.com/analytics/answer/1033867), if only for page access from source code repositories #572

**Comment by mjpitz** [comment]
So Hugo has some built-in semantics for handling breadcrumbs. Here's a thread describing it: https://discourse.gohugo.io/t/snippet-partial-for-creating-breadcrumbs-uses-bootstrap-4/15426

Here's it being used in the Docsy theme:
https://github.com/google/docsy/blob/master/layouts/partials/breadcrumb.html

**Comment by mjpitz** [comment]
I put up a PR that adds `date` to most of the content based on their last modification in git. Not sure how to configure `changefreq`. First time I'm seeing that one.

**Comment by mjpitz** [comment]
Looks like changefreq should be as easy as setting some configuration in `config.yaml`: https://gohugo.io/templates/sitemap-template/

**Comment by chalin** [comment]
Closed by #561
(Will track the two remaining items via their own issues.)
