### ISSUE TITLE
Migrate site to use the Hugo docsy theme

### ISSUE THREAD

**Issue by chalin** [grpc/grpc.io#479]
**Proposal document: [Docsy migration and site rework](https://docs.google.com/document/d/1GfbZh0YOr--01_fvGih8SuAP4FcGzgCZRvl02_OiCRM)** -- see the document for a statement of purpose and rework details.

---

Migrating to [docsy](https://github.com/google/docsy) should help address the following specific issues (note that some of these items have been carried over from #107):

- [→] Setup multi-site search, to include CNFC blog, etc #521
- [→] Analytics and SEO improvements #362
- [x] Add breadcrumbs for at least the language pages - #233
- [x] Make page titles unique - #363
- [x] Support in-page TOCs for mobile and maybe desktop too #169
- [x] Navigation sidebar cannot easily be scrolled #217
- [x] Switch to using Google search #520
- [x] Sidenav: show leaf pages under platforms #549

---

Possible prep work:

- [x] Create a `docsy` branch
- [x] Add docsy submodule to main - #228, #544
- [x] Consider: Move site pages into `content/en` #505

**Comment by chalin** [comment]
It seems that **[opentelemetry.io](https://opentelemetry.io) migrated to docsy** a month ago via this initial PR: [Site Refresh #247](https://github.com/open-telemetry/opentelemetry.io/pull/247) -- here's the related issue, [opentelemetry.io #203](https://github.com/open-telemetry/opentelemetry.io/issues/203).

cc @zacharysarah @celestehorgan @nate-double-u -- FYI, I'm not sure if you were aware of this migration. I like the result. (Also, notice how clean their footer is 😄 -- an issue which I've raised for grpc.io (#456))

**Comment by zacharysarah** [comment]
@chalin I didn’t know about their migration, but I agree it looks great!

**Comment by austinlparker** [comment]
Thanks! If y'all have any questions about our migration let me know. It was fairly straightforward.

**Comment by chalin** [comment]
Done! 🎉 (Will track the two remaining items via their own issues.)

**Comment by chalin** [comment]
I've deleted the `docsy` branch, as agreed during our sync, and removed the branch from [Netlify Deploy contexts for grpc.io](https://app.netlify.com/sites/grpc-io/settings/deploys#deploy-contexts).
