### ISSUE TITLE
Docsy migration followup items (2021/01)

### ISSUE THREAD

**Issue by chalin** [grpc/grpc.io#613]
Work items in follow up to #479:
- [x] docsy submodule was regressed to May 2020 #603
- [x] Google Search Console is reporting lots of errors #600
- [x] Prevent indexing of the old GitHub-pages site (#599)
- [ ] Allow indexing of API docs published from grpc/grpc (#612)
- [ ] Clean up & refresh npm packages -- drop bulma

**Comment by rubulubu** [comment]
> Work items in follow up to #479:
> 
> * [x]  Update README with site cloning instructions now that we have submodules [Update README with site cloning instructions now that we have submodules #594](https://github.com/grpc/grpc.io/issues/594)
> * [ ]  Duplicate partial inclusion in head.html and head-end.html [Duplicate partial inclusion in head.html and head-end.html #775](https://github.com/grpc/grpc.io/issues/775)
>   
>   * [ ]  HTML head meta elements are duplicated [HTML head meta elements are duplicated #745](https://github.com/grpc/grpc.io/issues/745)
>   * [ ]  Homepage has empty title/name for opengraph, twitter, and itemprop [Homepage has empty title/name for opengraph, twitter, and itemprop #744](https://github.com/grpc/grpc.io/issues/744)
> * [x]  Reducing technical debt
>   
>   * [x]  Create and use a grpc-docsy theme to hold docsy file overrides [Create and use a grpc.io-docsy theme to hold docsy file overrides #669](https://github.com/grpc/grpc.io/issues/669)
>   * [x]  Npm packages: drop bulma -- it isn't used anymore -- refresh other packages [Npm packages: drop bulma, refresh other packages #614](https://github.com/grpc/grpc.io/issues/614)
>   * [x]  Drop unused `figure.html` shortcode [Drop unused figure.html shortcode #678](https://github.com/grpc/grpc.io/pull/678)
>   * [x]  Drop style.sass since we aren't using bulma anymore [Drop style.sass since we aren't using bulma anymore #642](https://github.com/grpc/grpc.io/pull/642)
>   * [x]  Config file has dead code from pre-docsy times [Config file has dead code from pre-docsy times #655](https://github.com/grpc/grpc.io/issues/655)
>   * [x]  Use `assets/scss/_styles_project.scss` to include project-specific styling [Use assets/scss/_styles_project.scss to include project-specific styling #700](https://github.com/grpc/grpc.io/issues/700)
>     
>     * [x]  SCSS: revert import order of site variables? [SCSS: revert import order of site variables? #668](https://github.com/grpc/grpc.io/issues/668) Fixed via [SCSS: fix the relative import order of variables and variables_project #702](https://github.com/grpc/grpc.io/pull/702)
>   * [x]  SCSS: why redefine $gray-100? [SCSS: why redefine $gray-100? #703](https://github.com/grpc/grpc.io/issues/703)
> * [x]  SEO:
>   
>   * [x]  Google Search Console is reporting lots of errors [Google Search Console is reporting lots of errors (2021/01) #600](https://github.com/grpc/grpc.io/issues/600)
>   * [x]  Prevent indexing of the old GitHub-pages site ([Prevent indexing of the old GH-pages site #599](https://github.com/grpc/grpc.io/issues/599))
>   * [x]  Allow indexing of API docs published from grpc/grpc ([Allow indexing of API docs published from grpc/grpc #612](https://github.com/grpc/grpc.io/issues/612))
> * [x]  Regression:
>   
>   * [x]  docsy submodule was regressed to May 2020 [docsy submodule was regressed to May 2020 version by last PR #603](https://github.com/grpc/grpc.io/issues/603)
>   * [x]  Layout issue with Showcase page [Layout issue with Showcase page #630](https://github.com/grpc/grpc.io/issues/630)
>   * [x]  Footer updates are needed [Footer updates are needed #660](https://github.com/grpc/grpc.io/issues/660)
> * [ ]  Cleanup
>   
>   * [ ]  Config: revisit meta tags including those for Twitter and Open Graph [Config: revisit meta tags including those for Twitter and Open Graph #657](https://github.com/grpc/grpc.io/issues/657)
>   * [x]  Homepage isn't mobile friendly [Homepage isn't mobile friendly #689](https://github.com/grpc/grpc.io/issues/689)
>   * [x]  Homepage: fix logo and image sizes, they're too big [Homepage: fix logo and image sizes, they're too big #696](https://github.com/grpc/grpc.io/issues/696)
>     
>     * [x]  Homepage: docsy & styles cleanup, slight redesign to reduce oversized element sizes [Homepage: docsy & styles cleanup, slight redesign to reduce oversized element sizes #695](https://github.com/grpc/grpc.io/pull/695)
> * [x]  [Blog entries: external links should have external-link icon and have a blank target #582](https://github.com/grpc/grpc.io/issues/582)
> * [ ]  [Ensure that shortcode calls use % delimiters if they contain markdown #623](https://github.com/grpc/grpc.io/issues/623)
> * [x]  Upgrade to latest docsy version (2021/02) [Upgrade to latest docsy version (2021/02) #610](https://github.com/grpc/grpc.io/issues/610)
> 
> Questions (not addressed in previous points):
> 
> * [ ]  Use a shared layout for the About, Showcase and Community pages? [Use a shared layout for the About, Showcase and Community pages? #667](https://github.com/grpc/grpc.io/issues/667)
