### ISSUE TITLE
Improve Community & Contributing pages

### ISSUE THREAD

**Issue by chalin** [grpc/grpc.io#618]
There has been discussion for some time of improving the [Community][] page. I'm creating this issue as a place for discussion concerning the desired improvements.  Note that any cleanup & rework of the Community page should probably also include the [Contributing to gRPC][] page.

Community page:

- [x] Reworked community page #638, #644
- [x] Community page: cleanup styling (removed temporary embedded styles). #645
- [x] gRPC Community Meetup: determine which document to link to, and whether the bit.ly shortcut will be used.

Contributing page:

- [x] Eliminate grpc.io/contribute and inline appropriate text (adding it to the Community page) #618

Followup:
- Update https://github.com/grpc/grpc-community pages

[Community]: https://grpc.io/community/
[Contributing to gRPC]: https://grpc.io/contribute/

cc @thisisnotapril @macruzbar

**Comment by chalin** [comment]
Considering this complete.
